spring:
  cache:
    type: jcache # jcache는 java에서 제공하는 cache 추상화이고 hazelcast는 이 cache 추상화의 구현체를 제공
    jcache:
      provider: com.hazelcast.cache.HazelcastMemberCachingProvider
      # Cache를 관리하는 CacheManager를 관리하는 CachingProvider설정
      # 로컬 캐시일 경우 - HazelcastMemberCachingProvider
      # 리모트 캐시일 경우 - HazelcastClientCachingProvider
  hazelcast:
    config: "classpath:cacheconfig/hazelcast.yaml"

  datasource:
    url: jdbc:mysql://localhost:3306/subway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: masterpw

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      cloudwatch:
        batch-size: '20'
        namespace: 'sgo8308'

server:
  tomcat:
    mbeanregistry:
      enabled: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
