spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subway
    #    url: jdbc:mysql://192.168.100.134:3306/subway
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: masterpw
  cache:
    cache-names: "lines,path"
    redis:
      time-to-live: "1h"

  data:
    redis:
      host: localhost
      password:
      port: 6379

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      cloudwatch:
        batch-size: '20'
        namespace: 'sgo8308'

server:
  tomcat:
    mbeanregistry:
      enabled: true

cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: 'false'
